# Generated by Django 2.1.7 on 2019-08-30 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacao',
            name='cidade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacao',
            name='capacidade',
            field=models.DecimalField(decimal_places=1, help_text='Qual a capacidade do reservatório? Ex: 10.500 litros', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='local',
            field=models.CharField(help_text='Ex: casa, empresa, casa de campo', max_length=50, verbose_name='Local da Estação'),
        ),
    ]
