# Generated by Django 2.1.7 on 2019-08-31 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20190830_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=2, help_text='Digite seu CPF', max_length=11, verbose_name='Qual seu cpf?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estacao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='pessoa.Estacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacao',
            name='capacidade',
            field=models.DecimalField(decimal_places=1, help_text='Qual a capacidade do reservatório? Ex: 10.500 litros', max_digits=15, null=True),
        ),
    ]
