# Generated by Django 2.1.7 on 2019-09-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_auto_20190831_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(help_text='Ex: Janeiro', max_length=50, verbose_name='Mês')),
                ('ano', models.DecimalField(decimal_places=1, help_text='Ex: 2018', max_digits=15, null=True)),
                ('quantidade', models.DecimalField(decimal_places=1, help_text='18', max_digits=15, null=True)),
                ('valor', models.DecimalField(decimal_places=1, help_text='1000', max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsensor', models.CharField(help_text='Ex: casa, empresa, casa de campo', max_length=50, verbose_name='Local da Estação')),
                ('tipo', models.DecimalField(decimal_places=1, help_text='Qual a capacidade do reservatório? Ex: 10.500 litros', max_digits=15, null=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.Estacao')),
            ],
        ),
    ]
