# Generated by Django 2.1.7 on 2019-09-07 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0004_historicoconsumo_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Casa, Empresa, Casa de Campo.', max_length=50, verbose_name='Tipo de Estação')),
            ],
        ),
        migrations.AddField(
            model_name='estacao',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicoconsumo',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estacao',
            name='capacidade',
            field=models.DecimalField(decimal_places=1, help_text='Qual a capacidade do reservatório? Ex: 10.500 litros.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estacao',
            name='local',
            field=models.CharField(help_text='Ex: casa, empresa, casa de campo.', max_length=50, verbose_name='Local da Estação'),
        ),
        migrations.AlterField(
            model_name='historicoconsumo',
            name='ano',
            field=models.CharField(help_text='Ex: 2018', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicoconsumo',
            name='mes',
            field=models.CharField(help_text='Ex: Janeiro', max_length=15, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='historicoconsumo',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, help_text='18', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicoconsumo',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='1000', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='Digite seu CPF?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Digite seu nome?'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='idsensor',
            field=models.CharField(help_text='Ex: 1XXEDKE23', max_length=50, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(default=0, help_text='Qual tipo de sensor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estacao',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='pessoa.TipoEstacao'),
            preserve_default=False,
        ),
    ]
