# Generated by Django 2.1.7 on 2019-09-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20190906_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='usuario',
        ),
    ]
