# Generated by Django 2.1.7 on 2019-11-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_pessoa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='estacao',
        ),
        migrations.AlterField(
            model_name='estacao',
            name='capacidade',
            field=models.IntegerField(default=0, help_text='Qual a capacidade do reservatório? Ex: 10.500 litros.', null=True),
        ),
    ]
