# Generated by Django 2.1.7 on 2019-11-29 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0009_auto_20191108_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacao',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tipoestacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
